#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    hours = int(s[:2])
    period = s[-2:]
    h = s[:2]
    if hours == 12 and period =='AM':
        h = '00'
    elif hours in range(1,12) and period == 'PM':
        h = f'{hours+12}'
    
    time = h + s[2:-2]
    
    return time    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
